[package]
name = "mapla"
description = "The Mapla Compiler"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/oMatheuss/mapla"
license = "MIT"
readme = "README.md"
keywords = ["compiler", "language"]
categories = ["compilers"]

[dependencies]


[lints.rust]
unsafe_code = "forbid"
